FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai

SHELL ["/bin/bash", "-c"]

# 工具组
RUN apt-get update  && apt-get upgrade -y  && \
    apt-get install -y \
    apt-utils \
    curl wget \
    cmake make automake \
    openssh-server \
    net-tools \
    vim \
    git \
    gcc g++ \
    unzip

# x11依赖项
RUN apt-get install -y  \
    libx11-xcb1 \
    libfreetype6 \
    libdbus-1-3 \
    libfontconfig1 \
    libxkbcommon0   \
    libxkbcommon-x11-0

# python
RUN apt-get install -y \
    python-dev \
    python-pip \
    python3-dev \
    python3-pip \
    python-all-dev


# opencv需要
RUN apt-get install -y \
    libc-ares-dev \
    libssl-dev \
    build-essential \
    libboost-all-dev \
    libgtk2.0-dev \
    libavcodec-dev \
    libavformat-dev \
    libjpeg.dev \
    libtiff5.dev \
    libswscale-dev

ARG TARGETARCH
COPY install/libjasper /tmp/install/libjasper
RUN if [ "$TARGETARCH" = "amd64" ]; then \
        echo "Installing libjasper for amd64"; \
        chmod 777 /tmp/install/libjasper/install_libjasper_amd64.sh; \
        /tmp/install/libjasper/install_libjasper_amd64.sh; \
    elif [ "$TARGETARCH" = "arm64" ]; then \
        echo "Installing libjasper for arm64"; \
        chmod 777 /tmp/install/libjasper/install_libjasper_arm64.sh; \
        /tmp/install/libjasper/install_libjasper_arm64.sh; \
    else \
        echo "Unsupported architecture for install libjasper: $TARGETARCH"; \
        exit 1; \
    fi

# pangolin需要
RUN apt-get install -y \
    libgl1-mesa-dev \
    libglew-dev \
    libboost-dev \
    libboost-thread-dev \
    libboost-filesystem-dev \
    libpython2.7-dev \
    libglu1-mesa-dev freeglut3-dev

COPY install/pangolin /tmp/install/pangolin
RUN chmod 777 /tmp/install/pangolin/install_pangolin.sh && \
    /tmp/install/pangolin/install_pangolin.sh

COPY install/opencv /tmp/install/opencv
RUN chmod 777 /tmp/install/opencv/install_opencv.sh && \ 
    /tmp/install/opencv/install_opencv.sh

COPY install/eigen /tmp/install/eigen
RUN chmod 777 /tmp/install/eigen/install_eigen.sh && \
    /tmp/install/eigen/install_eigen.sh

COPY install/pytorch /tmp/install/pytorch
RUN chmod 777 /tmp/install/pytorch/install_pytorch.sh && \
    /tmp/install/pytorch/install_pytorch.sh
